version: "3.7"
services:
  bookstore-app:
    image: ahmed14java/maxab:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - maxab-network
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=maxab
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - maxab-network
networks:
  maxab-network:
